FROM amazoncorretto:8u312-alpine3.15

COPY ./target/products-service-backend-0.0.1-SNAPSHOT.jar ./var/lib/products-service-backend.jar

ENTRYPOINT ["java", "-jar", "/var/lib/products-service-backend.jar"]