apiVersion: v1
kind: Service
metadata:
  name: postgres-state-svc
  namespace: nagp-kns
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres-state
  selector:
    app: postgres-state